services:
  mongoDB:
    image: mongo:8.0
    container_name: mongoDB
    ports:
      - "27017:27017"
    volumes:
      - ./mongoDB:/data/db
    networks:
      - backend
    restart: always

networks:
  backend:
